### ISSUE TITLE
Crash when starting the app: Could not load the Qt platform plugin "xcb" in "" even though it was found

### ISSUE THREAD

**Issue by SimonCariou** [juleaume/bug_reporter#2]
On ubuntu 16.04

(bug_report) equipe@PAR-1922-LA:~/Documents/Simon/bug_reporter$ python -V
Python 3.6.12

(bug_report) equipe@PAR-1922-LA:~/Documents/Simon/bug_reporter$ pip freeze
PySide2==5.15.2
shiboken2==5.15.2

Crash dump logs:
(bug_report) equipe@PAR-1922-LA:~/Documents/Simon/bug_reporter$ python main.py 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Abandon (core dumped)

**Comment by SimonCariou** [comment]
Fix:

sudo apt-get install --reinstall libxcb-xinerama0

**Comment by SimonCariou** [comment]
https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without/1069502#1069502

**Comment by juleaume** [comment]
Won't fix for now
