### ISSUE TITLE
Window height doesn't fit small laptop screens

### ISSUE THREAD

**Issue by SimonCariou** [juleaume/bug_reporter#3]
On my computer, when opening the main window, I can neither see nor fill the fields below the attachments.
Since the height is not realizable I'm stuck.
(Screenshot of the whole screen I didn't crop the bottom on purpose :p)
![image](https://user-images.githubusercontent.com/10740333/103658726-e4950b00-4f6b-11eb-8147-c5793dd49597.png)

Maybe think about more of a horizontal layout since the width is usually significantly bigger than the height.

FYI: Screen res.
![image](https://user-images.githubusercontent.com/10740333/103659123-5a997200-4f6c-11eb-885f-2b669544755d.png)

**Comment by juleaume** [comment]
Fixed in 0.3.0 : added scroll bar
